# -*- coding: utf-8 -*-
"""Trending youtube video .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1M44GzPdBA5bu9C0zd_Z3IUSYU68QQA8w
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

import csv
df = pd.read_csv("/content/INvideos.csv",encoding='utf-8')
df.head()

df.shape

df.info()

df.isnull().sum()

df.duplicated().sum()

df.columns

df["description"]=df["description"].fillna=''

df.isnull().sum()

ndf=df["trending_date"].apply(lambda x: '20'+x[:2]).value_counts().to_frame().reset_index().rename(columns ={"index":"year", "trending_date":"no of videos"})
ndf

plt.bar(ndf["year"],ndf["no of videos"])

#what is the percentage of videos released in that particular year
df["trending_date"].apply(lambda x : "20"+x[:2]).value_counts(normalize =True)

df.describe()

df.hist("views")

df.hist("likes")

# percentage of videos with >50k likes
df[df["likes"]>50000]["likes"].count()/df["likes"].count()*100

df.hist("comment_count")

df.describe(include ="O")

#how do we calculate the length of title
df["title length"]= df['title'].apply(lambda x: len(x))
df.head(5)

plt.boxplot(df["title length"])

#is there any difference between no of views and title length
plt.scatter(df["title length"],df["views"])

df.corr()

#grouping of data based on catagory id
df.groupby("category_id").sum()

plt.bar(df["category_id"],df["views"])

plt.bar(df["category_id"],df["likes"])

df.info()

#how many videos got removed or had some error
df["video_error_or_removed"].value_counts()

#percentage of videos that have comment disabled
df["comments_disabled"].value_counts(normalize = True)

#how many videos have both comment disabled and rating disabled
len(df[(df["comments_disabled"] == True) & (df["ratings_disabled"]==True).index])

